# Generated by Django 5.2.9 on 2026-09-01 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y hora')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('event_type', models.CharField(choices=[('login_success', 'Inicio de sesión exitoso'), ('login_failed', 'Intento de login fallido'), ('logout', 'Cierre de sesión'), ('order_created', 'Pedido creado'), ('order_updated', 'Pedido actualizado'), ('product_created', 'Producto creado'), ('product_updated', 'Producto modificado'), ('stock_adjusted', 'Inventario ajustado')], db_index=True, max_length=40, verbose_name='Tipo de evento')),
                ('object_repr', models.CharField(blank=True, help_text='Representación legible del objeto (ej. "Pedido #42")', max_length=255, verbose_name='Objeto afectado')),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID del objeto')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Valores anteriores y nuevos en formato {"campo": {"before": ..., "after": ...}}', verbose_name='Cambios')),
                ('extra', models.JSONField(blank=True, default=dict, help_text='Datos adicionales de contexto (request path, agente, etc.)', verbose_name='Información extra')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Tipo de modelo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Bitácora de auditoría',
                'ordering': ['-timestamp'],
                'default_permissions': ('view',),
            },
        ),
    ]
