# Generated by Django 5.2.9 on 2026-09-01 04:11

import core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=core.encryption.EncryptedCharField(blank=True, default='', verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=core.encryption.EncryptedCharField(blank=True, default='', verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postal_code',
            field=core.encryption.EncryptedCharField(blank=True, default='', verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=core.encryption.EncryptedCharField(blank=True, default='', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='street',
            field=core.encryption.EncryptedCharField(blank=True, default='', verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=core.encryption.EncryptedCharField(blank=True, default='', verbose_name='Teléfono'),
        ),
    ]
