# Generated by Django 5.2.9 on 2026-09-01 04:11

import core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_birth_date_alter_order_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=core.encryption.EncryptedCharField(verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=core.encryption.EncryptedCharField(verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=core.encryption.EncryptedCharField(default='México', verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=core.encryption.EncryptedCharField(verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=core.encryption.EncryptedCharField(verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=core.encryption.EncryptedCharField(blank=True, default='', verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=core.encryption.EncryptedCharField(verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=core.encryption.EncryptedCharField(verbose_name='Estado / Provincia'),
        ),
    ]
