# Generated by Django 5.2.9 on 2026-08-28 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('author_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='Calificación')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('body', models.TextField(verbose_name='Comentario')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-created_at'],
            },
        ),
    ]
